apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-ui
  template:
    metadata:
      labels:
        app: bridge-ui
    spec:
      containers:
      - name: bridge-ui
        image: ghcr.io/project-death-star/death-star-bridge-ui:main # Placeholder, will be updated by CI/CD
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
