apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: ghcr.io/your-github-username/death-star-command-core:latest # Replace with your actual image path
        ports:
        - containerPort: 8080
